// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArv20kllozovcP1qKyLrCEJHVnvHUDpm8',
    appId: '1:615950408529:web:da43cbbeecee61e075d170',
    messagingSenderId: '615950408529',
    projectId: 'car-wash-app-86a16',
    authDomain: 'car-wash-app-86a16.firebaseapp.com',
    storageBucket: 'car-wash-app-86a16.appspot.com',
    measurementId: 'G-779C98FNRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPPhEMNXvyATQu7lCHX_Xu6a6eik0XtmM',
    appId: '1:615950408529:android:1c6b4ac60e99263975d170',
    messagingSenderId: '615950408529',
    projectId: 'car-wash-app-86a16',
    storageBucket: 'car-wash-app-86a16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCulnBU0Lr41-6GwxPGSR4zEbjD3VDqHFg',
    appId: '1:615950408529:ios:e882eb2b264f878f75d170',
    messagingSenderId: '615950408529',
    projectId: 'car-wash-app-86a16',
    storageBucket: 'car-wash-app-86a16.appspot.com',
    iosBundleId: 'com.example.carWashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCulnBU0Lr41-6GwxPGSR4zEbjD3VDqHFg',
    appId: '1:615950408529:ios:e882eb2b264f878f75d170',
    messagingSenderId: '615950408529',
    projectId: 'car-wash-app-86a16',
    storageBucket: 'car-wash-app-86a16.appspot.com',
    iosBundleId: 'com.example.carWashApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArv20kllozovcP1qKyLrCEJHVnvHUDpm8',
    appId: '1:615950408529:web:4c20e6f101dbe7e275d170',
    messagingSenderId: '615950408529',
    projectId: 'car-wash-app-86a16',
    authDomain: 'car-wash-app-86a16.firebaseapp.com',
    storageBucket: 'car-wash-app-86a16.appspot.com',
    measurementId: 'G-EB9LX8F2BL',
  );
}
